name: anytop_test
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py38h06a4308_0
  - python=3.8.15=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - blis==0.7.11
      - blobfile==3.0.0
      - catalogue==2.0.10
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - cymem==2.0.11
      - decorator==4.4.2
      - docopt==0.6.2
      - filelock==3.16.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - future==1.0.0
      - huggingface-hub==0.30.1
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - langcodes==3.4.1
      - language-data==1.3.0
      - lxml==5.3.2
      - marisa-trie==1.2.1
      - markupsafe==2.1.5
      - matplotlib==3.1.3
      - moviepy==1.0.3
      - mpmath==1.3.0
      - murmurhash==1.0.12
      - networkx==3.1
      - num2words==0.5.14
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.2
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - pillow==10.4.0
      - preshed==3.0.9
      - proglog==0.1.11
      - psutil==7.0.0
      - pycryptodomex==3.22.0
      - pymel==1.5.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scipy==1.10.1
      - sentencepiece==0.2.0
      - setuptools==75.3.2
      - six==1.17.0
      - smart-open==6.4.0
      - spacy==3.7.2
      - srsly==2.4.8
      - sympy==1.13.3
      - thinc==8.1.8
      - tokenizers==0.20.3
      - torch==2.4.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - triton==3.0.0
      - typer==0.4.2
      - typing-extensions>=4.8.0
      - urllib3==2.2.3
      - wasabi==0.10.1
      - zipp==3.20.2
prefix: /home/dcor/inbargat1/miniconda3/envs/anytop_new
